### ISSUE TITLE
When is the stable version released?

### ISSUE THREAD

**Issue by ilhanaydinli** [Tpojka/confer#1]
Hello there,
When is the stable version released?

I get this error when I click on the user list.

`(1/1) ErrorException
Undefined index: cluster
in ConferServiceProvider.php (line 30)`

**Comment by Tpojka** [comment]
@ilhanaydinli 

I wasn't available before, sorry. 
I took some time this weekend and tried to set this repository. 
It should work all except avatars that make some trouble here.  I will check it more thoroughly though.
Also will try to rewrite readme which seems has some mixed steps for now. 
Feel free to test it with `composer require --dev tpojka/confer`
